# Generated by Django 4.2.7 on 2024-03-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='city_id',
        ),
        migrations.AlterField(
            model_name='area',
            name='l1n1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='area',
            name='l2n2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cedative',
            name='bl1n1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='l1n1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='l2n2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wlsu',
            name='l1n1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='zone',
            name='l1n1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='zone',
            name='l2n2',
            field=models.TextField(),
        ),
    ]
